# Generated by Django 3.0.2 on 2020-01-13 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorial',
            name='tutorial_published',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 13, 16, 27, 39, 230657), verbose_name='date published'),
        ),
    ]
